# 해당 application-prod 는 배포를 위한 yml 파일입니다. 절대 Never 수정하시면 안됩니다.
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            scope:
              - email
              - profile

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  access-token-expired-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refresh-token-expired-time: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

logging:
  level:
    root: INFO