services:
  db:
    image: mysql:8.0.36
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: travel-db
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3333:3306"
    volumes: #데이터 저장
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    container_name: travel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: travel-elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch_8.7.1/data

volumes:
  app-data:
  mysql-data:
  redis-data:
  es-data: